### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by klaasnicolaas** [platformdroneracingnl/racing-events#209]
- [x] Improve the 404 page
- [x] Change the favicon
- [x] QR Code scanning with fysical device
